name: template
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.4.0
  riverpod_annotation: ^2.1.5
  freezed_annotation: ^2.4.1
  hooks_riverpod: ^2.4.0
  go_router: ^10.1.2
  flutter_animate: ^4.2.0+1
  flutter_hooks: ^0.20.1
  responsive_framework: ^1.1.1
  shared_preferences: ^2.2.1
  material_color_utilities: ^0.5.0
  font_awesome_flutter: ^10.5.0
  google_fonts: ^6.0.0
  device_preview: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  riverpod_generator: ^2.3.2
  build_runner: ^2.4.6
  custom_lint: ^0.5.3
  riverpod_lint: ^2.0.4
  freezed: ^2.4.2
  go_router_builder: ^2.0.1

flutter:
  uses-material-design: true
